# Exemplo de render.yaml
services:
  - type: web
    name: holistica-ia-backend
    env: python
    # Se você já tiver outras configurações como 'buildCommand', mantenha-as.
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    # Adicione esta linha:
    pre-deploy: "python manage.py migrate"
# ...
services:
  - type: web
    name: holistica-ia-backend
    env: python
    # ...
    # Adicione esta linha com os dois comandos:
    pre-deploy: "python manage.py migrate && python manage.py create_admin"