# Generated by Django 5.1 on 2025-06-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_groups_alter_usuario_tipo_and_more'),
    ]

    operations = [
    ]
