# Generated by Django 5.1 on 2025-07-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_paciente_terapeuta_mensagem_relatorio_sessao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AlterModelOptions(
            name='sessao',
            options={'ordering': ['-data'], 'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
    ]
