# Generated by Django 5.1 on 2025-07-10 19:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_usuario', models.TextField()),
                ('resposta_ia', models.TextField()),
                ('sentimento', models.CharField(max_length=20)),
                ('categoria_sentimento', models.CharField(max_length=50)),
                ('intensidade_sentimento', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sessao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='assunto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='emergencia_nome',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='emergencia_telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medicamentos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='terapeuta',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'terapeuta'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_terapeuta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='duracao',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=10),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='terapeuta',
            field=models.ForeignKey(limit_choices_to={'tipo': 'terapeuta'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_terapeuta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='crp',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CRP'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='especialidade',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Número inválido', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('terapeuta', 'Terapeuta'), ('admin', 'Administrador')], default='paciente', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
