# Generated by Django 5.1 on 2025-07-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_conversa_alter_mensagem_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversa',
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AlterModelOptions(
            name='sessao',
            options={'ordering': ['data'], 'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(default=1, limit_choices_to={'tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_paciente', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='terapeuta',
            field=models.ForeignKey(limit_choices_to={'tipo': 'terapeuta'}, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_terapeuta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='duracao',
            field=models.IntegerField(help_text='Duração em minutos'),
        ),
    ]
