# Generated by Django 5.1 on 2025-07-12 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_delete_conversa_alter_mensagem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='terapeuta',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'terapeuta'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_associados_terapeuta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_paciente_associado', to='usuarios.paciente'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_do_paciente', to='usuarios.paciente'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='terapeuta',
            field=models.ForeignKey(limit_choices_to={'tipo': 'terapeuta'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_como_terapeuta', to=settings.AUTH_USER_MODEL),
        ),
    ]
