# Generated by Django 5.1 on 2025-07-13 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_paciente_email_alter_paciente_terapeuta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='assunto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_recebidos', to='usuarios.paciente'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='terapeuta',
            field=models.ForeignKey(limit_choices_to={'tipo': 'terapeuta'}, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
