# Generated by Django 5.1 on 2025-07-14 02:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_mensagem_assunto_alter_relatorio_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('geral', 'Geral'), ('sessao', 'Sessão'), ('mensagem', 'Mensagem'), ('alerta', 'Alerta'), ('sistema', 'Sistema')], default='geral', max_length=20, verbose_name='Tipo')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
