# Generated by Django 5.1 on 2025-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversa',
            old_name='data_criacao',
            new_name='data_conversa',
        ),
        migrations.AddField(
            model_name='conversa',
            name='categoria_sentimento',
            field=models.CharField(default='Neutro', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversa',
            name='intensidade_sentimento',
            field=models.CharField(default='Baixa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversa',
            name='sentimento',
            field=models.CharField(default='Neutro', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversa',
            name='mensagem_usuario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='resposta_ia',
            field=models.TextField(),
        ),
    ]
