# Generated by Django 5.1 on 2025-07-11 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_rename_data_criacao_conversa_data_conversa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversa',
            options={'ordering': ['-data_conversa'], 'verbose_name': 'Conversa com IA', 'verbose_name_plural': 'Conversas com IA'},
        ),
        migrations.AddField(
            model_name='conversa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to=settings.AUTH_USER_MODEL),
        ),
    ]
