# Generated by Django 5.1 on 2025-07-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0003_alter_conversa_options_conversa_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversa',
            options={'ordering': ['-data_conversa'], 'verbose_name': 'Conversa IA', 'verbose_name_plural': 'Conversas IA'},
        ),
        migrations.AlterField(
            model_name='conversa',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversas_ia', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
